ALTER TABLE files
ADD COLUMN
"status" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE files
ADD COLUMN
"sha1" VARCHAR(64) NOT NULL DEFAULT '';

ALTER TABLE dirs
ADD COLUMN
"path" TEXT NOT NULL DEFAULT '';

ALTER TABLE files
ADD COLUMN
"path" TEXT NOT NULL DEFAULT '';
